services:
    backend:
      build: .
      environment:
          - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      ports:
          - "8000:8000"
      depends_on:
          - db
    db:
      image: postgres:16.1-alpine3.19
      environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
          - "5432:5432"
